Add new topics (conditionally change a band's visibility and reorder table cells)
VeraGorbyliova/dotnet-eud pull request #7
Opened 2019-07-23 07:00 UTC by VeraGorbyliova

2019-07-23 11:12 UTC, dirk-pieterse requested changes

2019-07-23 11:12 UTC, dirk-pieterse commented on interface-elements-for-desktop/articles/report-designer/report-designer-for-winforms/shape-report-data/shape-data-data-bindings/conditionally-change-a-bands-visibility-data-binding.md
> +	- Select a report and click its smart tag. In the invoked actions list, click the ellipsis button for the **FormattingRules** property.
```suggestion
	- Select a report and click its smart tag. In the invoked actions list, click the **FormattingRules** property's ellipsis button.
```

2019-07-23 11:12 UTC, dirk-pieterse commented on interface-elements-for-desktop/articles/report-designer/report-designer-for-winforms/shape-report-data/shape-data-data-bindings/conditionally-change-a-bands-visibility-data-binding.md
> +	- In the invoked **Formatting Rules Editor**, click the **Edit Rule Sheet...** button. The button invokes the **Formatting Rule Sheet Editor**. Click ![Buttons_Plus](../../../../../images/buttons_pl
```suggestion
	- In the **Formatting Rules Editor**, click the **Edit Rule Sheet...** button to invoke the **Formatting Rule Sheet Editor**. Click ![Buttons_Plus](../../../../../images/buttons_plus8644.png) to create a new formatting rule.
```

2019-07-23 11:12 UTC, dirk-pieterse commented on interface-elements-for-desktop/articles/report-designer/report-designer-for-winforms/shape-report-data/shape-data-data-bindings/conditionally-change-a-bands-visibility-data-binding.md
> +  	- Specify a condition for the rule. Click the ellipsis button for the rule's **Condition** property. In the invoked **Formatting Rules Editor**, specify the required expression.
```suggestion
  	- Specify a condition for the rule. Click the ellipsis button for the rule's **Condition** property and specify the expression in the invoked **Formatting Rules Editor**.
```

2019-07-23 11:12 UTC, dirk-pieterse commented on interface-elements-for-desktop/articles/report-designer/report-designer-for-winforms/shape-report-data/shape-data-data-bindings/conditionally-change-a-bands-visibility-data-binding.md
> +	  Here, the **[Discontinued] == true** expression is set for the **formattingRule1**  and the **[Discontinued] == false** expression - for the **formattingRule2**.
```suggestion
	  Here, the **formattingRule1** is set to **[Discontinued] == true**  and the **formattingRule2** is set to **[Discontinued] == false**. 
```

2019-07-23 11:12 UTC, dirk-pieterse commented on interface-elements-for-desktop/articles/report-designer/report-designer-for-winforms/shape-report-data/shape-data-data-bindings/conditionally-change-a-bands-visibility-data-binding.md
> +	Invoke the **Formatting Rules Editor** for a selected a band and move a rule to the **Rules applied to a control** section.
```suggestion
	Select a band, invoke the **Formatting Rules Editor**, and move a rule to the **Rules applied to a control** section.
```

2019-07-23 11:12 UTC, dirk-pieterse commented on interface-elements-for-desktop/articles/report-designer/report-designer-for-winforms/shape-report-data/shape-data-data-bindings/conditionally-change-a-bands-visibility-data-binding.md
> +	Here, the **formattingRule1** is applied to the **SubBand1**, and the **formattingRule2** - to the **SubBand2**.
```suggestion
	Here, the **formattingRule1** is applied to **SubBand1**, and the **formattingRule2** to **SubBand2**.
```

2019-07-23 11:12 UTC, dirk-pieterse commented on interface-elements-for-desktop/articles/report-designer/report-designer-for-winforms/shape-report-data/shape-data-expression-bindings/conditionally-change-a-bands-visibility-expression-bindings.md
> +This topic describes how to change report band visibility.
```suggestion
This topic describes how to change the report band's visibility.
```

2019-07-23 11:12 UTC, dirk-pieterse commented on interface-elements-for-desktop/articles/report-designer/report-designer-for-winforms/shape-report-data/shape-data-expression-bindings/conditionally-change-a-bands-visibility-expression-bindings.md
> +1. Select the required band and switch to the **Properties** panel. Choose **Expressions** ![](../../../../../images/conditionally-change-a-bands-visibility-expression-button.png) and click the **Vis
```suggestion
1. Select a band and switch to the **Properties** panel. Choose **Expressions** ![](../../../../../images/conditionally-change-a-bands-visibility-expression-button.png) and click the **Visible** property's ellipsis button.
```

2019-07-23 11:12 UTC, dirk-pieterse commented on interface-elements-for-desktop/articles/report-designer/report-designer-for-winforms/shape-report-data/shape-data-expression-bindings/conditionally-change-a-bands-visibility-expression-bindings.md
> +2. In the invoked **Expression Editor**, specify the required expression.
```suggestion
2. In the invoked **Expression Editor**, specify the expression.
```

2019-07-23 11:12 UTC, dirk-pieterse commented on interface-elements-for-web/articles/report-designer/use-report-elements/use-tables/manipulate-table-elements.md
>  You can stretch a cell so that it occupies several rows and columns. To stretch a cell across several columns, remove a neighboring cell by pressing DELETE or selecting the **Delete Cell** command in
```suggestion
You can stretch a cell to occupy several rows and columns. To stretch a cell across several columns, press DELETE or select the **Delete Cell** command in the **Action** category to remove a neighboring cell.
```

2019-07-23 11:12 UTC, dirk-pieterse commented on interface-elements-for-web/articles/report-designer/use-report-elements/use-tables/manipulate-table-elements.md
> +In [Report Explorer](../../report-designer-tools/ui-panels/report-explorer.md) you can change the order of table cells. Select a cell and drag it to a new position.
```suggestion
You can change table cells' order in the [Report Explorer](../../report-designer-tools/ui-panels/report-explorer.md). To do this, select a cell and drag it to a new position.
```

2019-07-23 11:27 UTC, VeraGorbyliova commented on interface-elements-for-desktop/articles/report-designer/report-designer-for-winforms/shape-report-data/shape-data-data-bindings/conditionally-change-a-bands-visibility-data-binding.md
> +	  Here, the **[Discontinued] == true** expression is set for the **formattingRule1**  and the **[Discontinued] == false** expression - for the **formattingRule2**.
Why you use a dot after the word 'Here'? What do you mean?

2019-07-23 11:38 UTC, VeraGorbyliova commented on interface-elements-for-desktop/articles/report-designer/report-designer-for-winforms/shape-report-data/shape-data-data-bindings/conditionally-change-a-bands-visibility-data-binding.md
> +	  Here, the **[Discontinued] == true** expression is set for the **formattingRule1**  and the **[Discontinued] == false** expression - for the **formattingRule2**.
You use dot after 'Here'. What do you mean?

2019-07-24 05:29 UTC, dirk-pieterse requested changes

2019-07-24 05:29 UTC, dirk-pieterse commented on interface-elements-for-desktop/articles/report-designer/report-designer-for-winforms/shape-report-data/shape-data-data-bindings/conditionally-change-a-bands-visibility-data-binding.md
> +	  Here, the **[Discontinued] == true** expression is set for the **formattingRule1**  and the **[Discontinued] == false** expression - for the **formattingRule2**.
I accidentally changed the comma after 'Here' to a period.

2019-07-24 05:29 UTC, dirk-pieterse commented on interface-elements-for-desktop/articles/report-designer/report-designer-for-winforms/shape-report-data/shape-data-data-bindings/conditionally-change-a-bands-visibility-data-binding.md
> +	  Here, the **[Discontinued] == true** expression is set for the **formattingRule1**  and the **[Discontinued] == false** expression - for the **formattingRule2**.
However, you use 'Here,' too many times. I suggest removing it or using an alternative.

2019-07-30 12:56 UTC, merged